apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejsnetlifyfrontend
spec:
  selector:
    matchLabels:
      app: vuejsnetlify
  replicas: 3
  template:
    metadata:
      labels:
        app: vuejsnetlify
    spec:
      containers:
      - name: vuejsnetify
        image: simoncarr/vuejs_netlify:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
