apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs-netlify-frontend
spec:
  selector:
    matchLabels:
      app: vuejs-netlify
  replicas: 3
  template:
    metadata:
      labels:
        app: vuejs-netlify
    spec:
      containers:
      - name: vuejs-netify
        image: simoncarr/vuejs_netlify:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
