apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs-netlify-frontend
spec:
  selector:
    matchLabels:
      app: vuejs-netlify
  replicas: 3
  template:
    metadata:
      labels:
        app: vuejs-netlify
    spec:
      containers:
      - name: vuejs-netify
        image: simoncarr/vuejs_netlify:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vuejs-netlify-service
  labels:
    run: vuejs-netlify
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: vuejs-netlify
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: "nginx-ingress.web.simoncarr.co.uk"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: vuejs-netlify
            port:
              number: 80
